# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: ObjectName
    displayName: Enter the process name to be deployed
    type: string
  - name: ProcessID
    displayName: Enter the processID to be deployed
    type: string
  - name: TargetEnv
    displayName: Enter the target Environment
    type: string
  - name: ObjectVersion
    displayName: Enter the version of the package
    type: string

steps:
- script: echo "Below are the details of the process to be deployed"
      '\n' ${{parameters.ObjectName}}
      '\n' ${{parameters.ProcessID}}
      '\n' ${{parameters.TargetEnv}}
      '\n' ${{parameters.ObjectVersion}}
  displayName: 'Automating Deployment in Boomi'
