# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr: none

pool:
  vmImage: ubuntu-latest
  
parameters:
- name: ProcessName
  displayName: Enter the process name ?
  type: string

steps:
- script: echo ${{parameters.ProcessName}} "is the process to be deployed in Boomi."
  displayName: 'Automating Deployment in Boomi !'
