# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr: none

pool:
  vmImage: ubuntu-latest
  
parameters:
- name: ProcessName
  displayName: Enter the process name ?
  type: string
- name: ProcessID
  displayName: Enter the process name ?
  type: string
- name: ProcessVersion
  displayName: Enter the process name ?
  type: string
- name: DeployNotes
  displayName: Enter the process name ?
  type: string
- name: TargetEnv_P
  displayName: Enter the process name ?
  type: string
- name: TargetEnv_T
  displayName: Enter the process name ?
  type: string

steps:
- script: echo -e "Below is the details of the process that is to be deployed.\n"
          echo ${{parameters.ProcessName}} $'\n'
          echo ${{parameters.ProcessID}} $'\n'
          echo ${{parameters.ProcessVersion}} $'\n'
          echo ${{parameters.DeployNotes}} $'\n'
          echo ${{parameters.TargetEnv_P}} $'\n'
          echo ${{parameters.TargetEnv_T}} $'\n'
  displayName: 'Automating Deployment in Boomi !'
